const games=[
{id:'ferris',t:'Ferris Game',s:'Playable GitHub Pages game',url:'https://ferristhiel.github.io/Game/',mb:1200,p:0,a:'#151923',b:'#505b6d'},
{id:'retro',t:'Retro Pixel Game',s:'Retro pixel adventure',url:'https://ferristhiel.github.io/Retro-Pixel-Game/',mb:640,p:0,a:'#ffcc28',b:'#7d4cff'},
{id:'three',t:'3D Game',s:'3D browser world',url:'https://ferristhiel.github.io/3D-Game/',mb:1800,p:0,a:'#2299ff',b:'#00dcb4'},
{id:'echo',t:'Echo Runner',s:'Hyper speed racing',mb:4200,p:19.99,a:'#f94a42',b:'#9d1d2b'},
{id:'void',t:'Void Garden',s:'Dream strategy world',mb:2600,p:0,a:'#6d42ff',b:'#1ec9ff'},
{id:'forge',t:'Lumen Forge',s:'Creative build universe',mb:5200,p:29.99,a:'#ff7a1f',b:'#ff2b79'}
];
const $=q=>document.querySelector(q);let sel=0,tab='games';
const K='aos-installed-v1',D='aos-downloads-v1',W='aos-wish-v1',C='aos-cart-v1',M='aos-media-v1',T='aos-dark-v1';
function get(k,d){try{return JSON.parse(localStorage.getItem(k))??d}catch{return d}}
function set(k,v){localStorage.setItem(k,JSON.stringify(v))}
function installed(){let x=get(K,null);if(!x){x={ferris:true};set(K,x)}return x}
function ok(id){return !!installed()[id]}
function add(id){let x=installed();x[id]=true;set(K,x)}
function dl(){return get(D,{})}
function saveDl(x){set(D,x)}
function now(){return new Date().toLocaleTimeString('de-DE',{hour:'2-digit',minute:'2-digit'})}
function user(){return get('aurora-console-active-user-v1',{name:'Ferro',avatar:'⚡'})}
function toast(m){const n=document.createElement('div');n.className='toast';n.textContent=m;document.body.appendChild(n);setTimeout(()=>n.remove(),2200)}
function boot(){setInterval(()=>{const g=$('#loginClock'),l=$('#live');if(g)g.textContent=now();if(l)l.textContent=now()},1000);$('#loginClock').textContent=now();renderUsers();$('#bootBtn').onclick=()=>{$('#boot').classList.add('hidden');setTimeout(()=>$('#login').classList.remove('hidden'),250)};setTimeout(()=>{$('#boot').classList.add('hidden');$('#login').classList.remove('hidden')},1300)}
function renderUsers(){let us=get('aos-users-v1',[{name:'Ferro',avatar:'⚡',main:true}]);const cards=[{create:true},...us,{guest:true}];const html=cards.map((u,i)=>`<button class="user ${u.main?'selected':''}" data-i="${i}"><span class="avatar">${u.create?'+':u.guest?'⚂':u.avatar}</span><h3>${u.create?'Create User':u.guest?'Play as Guest':u.name}</h3><p>${u.create?'Add a new user':u.guest?'Temporary profile':'Main Account'}</p></button>`).join('');$('#users').innerHTML=html;$('#usersMirror').innerHTML=html;$('#users').querySelectorAll('.user').forEach((b,i)=>b.onclick=()=>{let u=cards[i];if(u.create){let n=prompt('Name?');if(n){us.push({name:n,avatar:n.slice(0,2).toUpperCase()});set('aos-users-v1',us);renderUsers()}return}set('aurora-console-active-user-v1',u.guest?{name:'Guest',avatar:'⚂'}:u);$('#login').classList.add('hidden');toast((u.name||'Guest')+' angemeldet')})}
function top(){let u=user();return `<div class="top"><div class="left"><span id="live">${now()}</span><button onclick="shot()">📷 F</button><button onclick="status()">⬇ Status</button></div><div class="tabs"><button class="${tab==='media'?'on':''}" onclick="tab='media';draw()">Media</button><button class="${tab==='games'?'on':''}" onclick="tab='games';draw()">All</button><button class="${tab==='store'?'on':''}" onclick="tab='store';draw()">Store</button><button onclick="plus()">Aurora+</button><button class="${tab==='settings'?'on':''}" onclick="tab='settings';draw()">Settings</button></div><div class="right"><button onclick="friends()">👥</button><button onclick="profile()">${u.avatar} ${u.name}</button></div></div>`}
function draw(){if(tab==='store')return store();if(tab==='media')return media();if(tab==='settings')return settings();let g=games[sel],d=dl()[g.id],i=ok(g.id);$('#app').innerHTML=top()+`<section class="main"><div class="welcome"><h1>Welcome</h1><p>△○×□</p></div><div class="shelf"><div class="row">${games.map(tile).join('')}</div><div class="mirror">${games.map(tile).join('')}</div><div class="meta"><h2>${g.t}</h2><p>${i?g.s:d?'Download '+d.p+'% · '+Math.round(g.mb*(1-d.p/100))+' MB übrig':g.p?g.p.toFixed(2)+' € · Store':'Free Download · '+g.mb+' MB'}</p><button onclick="mainAction()">${i?'Spiel starten':d?'Status':g.p?'Kaufen':'Free Download'}</button> <button class="secondary" onclick="info()">Infos</button></div></div></section>`;$('#app').querySelectorAll('.row .tile').forEach(b=>b.onclick=()=>{let n=+b.dataset.n;if(n===sel)mainAction();else{sel=n;draw()}})}
function tile(g,n){let d=dl()[g.id],i=ok(g.id);return `<button class="tile ${n===sel?'sel':''} ${!i&&!d?'locked':''} ${d?'down':''}" data-n="${n}" style="--a:${g.a};--b:${g.b}"><span class="cover"><span class="sym">${i?'▶':d?'⬇':'▣'}</span><h3 class="name">${g.t}</h3>${d?`<span class="bar" style="--p:${d.p}%"><i></i></span>`:`<span class="enter">${i?'Enter':g.p?'Buy':'Free'}</span>`}</span></button>`}
function mainAction(){let g=games[sel],d=dl()[g.id];if(ok(g.id))return start(g);if(d)return status();download(g)}
function download(g){if(!confirm(`${g.p?g.p.toFixed(2)+' € kaufen':'Free Download'}: ${g.t}\n${g.mb} MB`))return;let x=dl();x[g.id]={p:0};saveDl(x);toast(g.t+' lädt herunter');draw();let t=setInterval(()=>{let y=dl();if(!y[g.id])return clearInterval(t);y[g.id].p=Math.min(100,y[g.id].p+10+Math.floor(Math.random()*15));if(y[g.id].p>=100){delete y[g.id];saveDl(y);add(g.id);clearInterval(t);toast(g.t+' ist installiert');draw();return}saveDl(y);draw()},650)}
function store(){let wish=get(W,{}),cart=get(C,{});$('#app').innerHTML=top()+`<section class="main"><div class="welcome"><h1>Store</h1><p>🛒 ♥ DOWNLOAD</p></div><div class="grid">${games.map(g=>`<div class="card"><h2>${g.t}</h2><p>${g.s}</p><p>${g.mb} MB · ${ok(g.id)?'Installiert':g.p?g.p.toFixed(2)+' €':'Free'}</p><button onclick="${ok(g.id)?'toast(\'Schon installiert\')':'download(games.find(x=>x.id==\''+g.id+'\'))'}">${ok(g.id)?'Installiert':g.p?'Kaufen':'Free Download'}</button> <button class="secondary" onclick="wish('${g.id}')">${wish[g.id]?'♥':'♡'}</button> <button class="secondary" onclick="cart('${g.id}')">${cart[g.id]?'🛒✓':'🛒'}</button></div>`).join('')}</div></section>`}
function wish(id){let x=get(W,{});x[id]=!x[id];set(W,x);toast(x[id]?'Wunschliste hinzugefügt':'Wunschliste entfernt');store()}
function cart(id){let x=get(C,{});x[id]=!x[id];set(C,x);toast(x[id]?'Im Einkaufswagen':'Aus Einkaufswagen entfernt');store()}
function media(){let shots=get(M,[]);$('#app').innerHTML=top()+`<section class="main"><div class="welcome"><h1>Media</h1><p>F = FOTO</p></div><div class="grid">${shots.length?shots.map(s=>`<div class="card"><h2>Screenshot</h2><p>${new Date(s.t).toLocaleString('de-DE')}</p><p>${s.screen}</p></div>`).join(''):'<div class="card"><h2>Noch keine Medien</h2><p>Drücke F für ein Foto.</p></div>'}</div></section>`}
function settings(){$('#app').innerHTML=top()+`<section class="main"><div class="welcome"><h1>Settings</h1><p>CLEAN / DARK</p></div><div class="grid"><div class="card"><h2>Clean Hintergrund</h2><p>${document.body.classList.contains('dark')?'Dunkel':'Weiß clean'}</p><button onclick="theme()">Umschalten</button></div><div class="card"><h2>Downloads</h2><p>Status und Speicher.</p><button onclick="status()">Öffnen</button></div><div class="card"><h2>Shortcuts</h2><p>F = Foto, Enter = Start, Pfeile = Auswahl.</p></div></div></section>`}
function theme(){document.body.classList.toggle('dark');set(T,document.body.classList.contains('dark'));draw()}
function shot(){let x=get(M,[]);x.unshift({t:new Date().toISOString(),screen:games[sel]?.t||tab});set(M,x.slice(0,50));toast('Screenshot gespeichert');if(tab==='media')media()}
function panel(h){closePanel();let p=document.createElement('div');p.className='panel';p.id='panel';p.innerHTML=h;document.body.appendChild(p)}function closePanel(){$('#panel')?.remove()}
function status(){let d=dl();panel(`<h2>Downloads</h2>${Object.keys(d).length?Object.entries(d).map(([id,v])=>{let g=games.find(x=>x.id===id);return `<div class="card"><b>${g.t}</b><p>${v.p}% · ${Math.round(g.mb*(1-v.p/100))} MB übrig</p><div class="line" style="--w:${v.p}%"><i></i></div></div>`}).join(''):'<p>Keine aktiven Downloads.</p>'}<button onclick="closePanel()">Schließen</button>`)}
function profile(){panel(`<h2>${user().name}</h2><div class="card"><b>Status</b><p>Online · ${now()}</p></div><div class="card"><b>Media</b><p>${get(M,[]).length} Screenshots</p></div><button onclick="friends()">Freunde</button> <button onclick="plus()">Aurora+</button>`)}
function friends(){panel(`<h2>Freunde</h2>${['Mira','Onyx','Kade','Nova'].map(n=>`<div class="card"><b>${n}</b><p>Online</p><button onclick="toast('Einladung an ${n} gesendet')">Einladen</button></div>`).join('')}`)}
function plus(){panel(`<h2>Aurora+</h2><div class="card"><b>Game Pass</b><p>Cloud Saves · Free Games · Early Access</p></div><button onclick="toast('Aurora+ Demo aktiviert')">Aktivieren</button>`)}
function info(){let g=games[sel];panel(`<h2>${g.t}</h2><div class="card"><p>${g.s}</p><p>${g.mb} MB</p><p>${ok(g.id)?'Installiert':'Nicht installiert'}</p></div>`)}
function start(g){$('#launch').classList.remove('hidden');$('#launchTitle').textContent=g.t;$('#loadbar').style.width='0';requestAnimationFrame(()=>$('#loadbar').style.width='100%');setTimeout(()=>{$('#launch').classList.add('hidden');if(g.url){$('#gameTitle').textContent=g.t;$('#openTab').href=g.url;$('#gameFrame').src=g.url;$('#gamePlayer').classList.remove('hidden')}else toast(g.t+' Demo gestartet')},1700)}
$('#closeGame').onclick=()=>{$('#gamePlayer').classList.add('hidden');$('#gameFrame').src='about:blank'};window.addEventListener('keydown',e=>{if(e.key==='ArrowRight'){sel=(sel+1)%games.length;draw()}if(e.key==='ArrowLeft'){sel=(sel-1+games.length)%games.length;draw()}if(e.key==='Enter')mainAction();if(e.key.toLowerCase()==='f')shot();if(e.key==='Escape')closePanel()});
if(get(T,false))document.body.classList.add('dark');boot();draw();
